### PR TITLE
restore params (#184)

### LINKED ISSUE #184: Add support for RPP
Right now only Box is available, we would like to have also a RPP ("rectangular cuboid") which has width, height and depth.
Take a look at this https://threejs.org/docs/index.html#api/en/geometries/BoxGeometry

Currently Box has only width
image

### PR DESCRIPTION
**Pull request by ostatni5**
close #184

### CODE REVIEW

**Comment by grzanka** [comment]
@ostatni5 

In this window:
image

can you replase label

`Width [cm]` with `X side length (width) [cm]` and similar for other axis.
This will clearly distinguish side length from half-length convention used in TOPAS

**Review by grzanka — CHANGES_REQUESTED** [review]
changes in comments

**Comment by ostatni5** [comment]
obraz

**Review by grzanka — APPROVED** [review]
good !

**Pull request merged**
