### PR TITLE
add beam definition

### PR DESCRIPTION
**Pull request by ostatni5**
v2:
image

v1:
image

### CODE REVIEW

**Review by Derstilon — CHANGES_REQUESTED** [review]
If we use beam configuration data, then many other parameters become obsolete. @grzanka can you confirm whitch parameters should be hidden when we use beam.dat
image

**Comment by grzanka** [comment]
We need to keep:
- [ ] number of primary particles
- [ ] particle type
- [ ] beam source position
- [ ] beam direction

Rest (energy, spread etc) should have an option to be replaced by content of the sobp.dat file

**Comment by grzanka** [comment]
What is that field you are proposing ? Should I be able to drag and drop file there ?

**Comment by grzanka** [comment]
New toogle button: "Beam model file" and "Simple beam". By default simple beam is selected:

image

**Comment by ostatni5** [comment]
image

**Comment by grzanka** [comment]
@ostatni5 what about changes in the converter ? can we merge this PR first (to have some reasonable JSON examples) and the work on the converter part ?

**Comment by ostatni5** [comment]
> @ostatni5 what about changes in the converter ? can we merge this PR first (to have some reasonable JSON examples) and the work on the converter part ?

JSON can be generated from this branch.

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
