### PR TITLE
Enable new loading of data

### PR DESCRIPTION
**Pull request by Derstilon**
Loading simulation results loads the editor as well.
You can now load the editor state from the simulation.
This pull request requires new features from [the latest backend pull request](https://github.com/yaptide/yaptide/pull/209)

### CODE REVIEW

**Comment by grzanka** [comment]
I am planning to test it with playbooks from https://github.com/yaptide/deploy :
```
ansible-playbook cloud_instance.yml -e "image_name='Ubuntu 20.04 LTS Snapshot 20221021'"
ansible-playbook site.yml -e frontend_repo_version='feature/load-various-data'
```

**Comment by grzanka** [comment]
@Derstilon do I need to regenerate examples to get this working ?

**Comment by Derstilon** [comment]
> @Derstilon do I need to regenerate examples to get this working ?

Examples from demo should be working. Old files I'm not so sure

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
