### PR TITLE
Feature/92 remove empty zone

### LINKED ISSUE #92: After deleting all bodies, zone stays on the list
I've created a couple of bodies, defined a zone a removed all bodies.
The bodies were properly removed, but the orphaned zone stayed on the list

image

### PR DESCRIPTION
**Pull request by ostatni5**
close #92

### CODE REVIEW

**Comment by grzanka** [comment]
Two problems: after adding a zone, it looks like a wireframe in 3D view.
image

Another problem - after removing bodies, orphaned zone still exists on list of objects.
image

**Comment by grzanka** [comment]
I've also checked zone display on master branch - it looks ok
image

**Comment by grzanka** [comment]
@ostatni5 Orphaned zone problem disappeared with 44a94ba, however bad display still persists

**Comment by grzanka** [comment]
With #217ac22 zone display is fixed
image

**Review by grzanka — APPROVED** [review]
Looks good

**Review by Derstilon — APPROVED** [review]

**Pull request merged**
