### PR TITLE
Feature/filter rules

### LINKED ISSUE #213: Add manager/creator for filters available for detectors
Some concrete example:
https://github.com/nbassler/PubSim/blob/master/2015_Guan/sim-files/template_H/detect.dat

See SH12A documentation
image

### PR DESCRIPTION
**Pull request by Derstilon**
image
Closes #213

### CODE REVIEW

**Comment by grzanka** [comment]
Why 4 rules are automatically added when single filter is added ?

**Comment by grzanka** [comment]
Is there a chance to select proton as particle id in the filter ?

**Comment by Derstilon** [comment]
> Is there a chance to select proton as particle id in the filter ?

Haven't seen this particle as an option for filters
image
Are you sure it should be there?

**Comment by grzanka** [comment]
Can you change the order to:

```
A, AMASS, AMU, Z, GEN, E, ENUC, EAMU, ID, NPRIM
```

?

image

**Comment by grzanka** [comment]
Can we have exact rule equation in the white rectangle just below "Add rule" 
image

After typing several rules user has to click on rule name to see what was implemented

**Comment by Derstilon** [comment]
> Can you change the order to:
> 
> ```
> A, AMASS, AMU, Z, GEN, E, ENUC, EAMU, ID, NPRIM
> ```

image

**Comment by grzanka** [comment]
> > Can you change the order to:
> > ```
> > A, AMASS, AMU, Z, GEN, E, ENUC, EAMU, ID, NPRIM
> > ```
> 
> image

Looks nice, was it pushed already ?

> > Can we have exact rule equation in the white rectangle just below "Add rule" image
> > After typing several rules user has to click on rule name to see what was implemented
> 
> Can we add it to the final configuration UI? Users will be able to double-check all filters applied to the scored quantities. There will be more space and more reasons to add this visualization.
> 
> Either way, we can add it after all important features are done. Can you write an issue for this?

Sure, I will add it.

**Comment by grzanka** [comment]
When user clicks on "Add rule" in filters section we should get by default "Z = 1" filter, not "AMU < ".

Moreover `Z` filter should have no units on RHS:
image

`GEN` filter should operate on integer, not floats and should have no units.
image

`A` filter should operate on integers, not floats, default value 4 is OK, but default operator should be `=`

`ENUC` should operate on floats, default should be `< 10. MeV/n`
image

`NPRIM` should operate on integers, default should be `= 2`
image

**Comment by grzanka** [comment]
App is crashing on adding first filter rule:

image

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
