### PR TITLE
use css properties insted of headings

### PR DESCRIPTION
**Pull request by matuszsmig**

### CODE REVIEW

**Comment by grzanka** [comment]
@matuszsmig do you expect more fixes in headings to come ?

**Comment by matuszsmig** [comment]
> @matuszsmig do you expect more fixes in headings to come ?

yes, I will be working on it

**Comment by grzanka** [comment]
@matuszsmig do we that `.idea` stuff ?

image

**Comment by matuszsmig** [comment]
@grzanka we don't need them.

Must have been some missclick, now it's ready

**Review by grzanka — APPROVED** [review]

**Pull request merged**
