### PR TITLE
Integrate new rest API

### PR DESCRIPTION
**Pull request by Derstilon**
Now works with
https://github.com/yaptide/yaptide/pull/241

### CODE REVIEW

**Comment by grzanka** [comment]
Problem with deploy:
```
TASK [backend : Insert a first user into database (without grid_proxy)] ***************************************************************************************************************
fatal: [yaptide]: FAILED! => {"changed": true, "rc": 1, "stderr": "Traceback (most recent call last):\n  File \"/usr/local/app/yaptide/admin/db_manage.py\", line 187, in <module>\n    run()\n  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1055, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n  File \"/usr/local/app/yaptide/admin/db_manage.py\", line 96, in add_user\n    users = db.Table(TableTypes.USER.value, metadata, autoload=True, autoload_with=engine)\n  File \"<string>\", line 2, in __new__\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py\", line 277, in warned\n    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 432, in __new__\n    return cls._new(*args, **kw)\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 486, in _new\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 482, in _new\n    table.__init__(name, metadata, *args, _no_init=False, **kw)\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 852, in __init__\n    self._extra_kwargs(**kw)\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 1000, in _extra_kwargs\n    self._validate_dialect_kwargs(kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/base.py\", line 558, in _validate_dialect_kwargs\n    raise TypeError(\nTypeError: Additional arguments should be named <dialectname>_<argument>, got 'autoload'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/app/yaptide/admin/db_manage.py\", line 187, in <module>", "    run()", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__", "    return self.main(*args, **kwargs)", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1055, in main", "    rv = self.invoke(ctx)", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke", "    return _process_result(sub_ctx.command.invoke(sub_ctx))", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke", "    return __callback(*args, **kwargs)", "  File \"/usr/local/app/yaptide/admin/db_manage.py\", line 96, in add_user", "    users = db.Table(TableTypes.USER.value, metadata, autoload=True, autoload_with=engine)", "  File \"<string>\", line 2, in __new__", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py\", line 277, in warned", "    return fn(*args, **kwargs)  # type: ignore[no-any-return]", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 432, in __new__", "    return cls._new(*args, **kw)", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 486, in _new", "    with util.safe_reraise():", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py\", line 147, in __exit__", "    raise exc_value.with_traceback(exc_tb)", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 482, in _new", "    table.__init__(name, metadata, *args, _no_init=False, **kw)", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 852, in __init__", "    self._extra_kwargs(**kw)", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py\", line 1000, in _extra_kwargs", "    self._validate_dialect_kwargs(kwargs)", "  File \"/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/base.py\", line 558, in _validate_dialect_kwargs", "    raise TypeError(", "TypeError: Additional arguments should be named <dialectname>_<argument>, got 'autoload'"], "stdout": "Adding user: admin", "stdout_lines": ["Adding user: admin"]}
```

**Comment by grzanka** [comment]
It seems that the autoload is gone, all parameters should have _ inside:
https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table

**Comment by p1003** [comment]
The fixes are going to be made in this PR: https://github.com/yaptide/yaptide/pull/252 @grzanka

**Comment by grzanka** [comment]
Seems to work, but require `shieldhit` binary version at least 1.0.0

**Review by grzanka — APPROVED** [review]

**Pull request merged**
