### PR TITLE
Use name of page in `key` in results

### PR DESCRIPTION
**Pull request by ostatni5**

### CODE REVIEW

**Review by grzanka — APPROVED** [review]

**Comment by grzanka** [comment]
It works well with normal project, then the bug is fixed, but when running from the files converted using pyodide converter there is an issue.

I've added by hand following section to detect.dat:
```
Output
    Filename z_profile.bdo
    Geo CylZ_Mesh
    Quantity Dose  
    Quantity Fluence Protons 
    Quantity Fluence Primaries 
    Quantity Fluence Secondary_protons 
    Quantity AvgEnergy Primaries 
    Quantity AvgEnergy Protons 
```
without grouping:
image
image
image


and here is the output when "Group Quantities" is selected:

image
image
image
image

the quantities appear both grouped and ungrouped

**Comment by grzanka** [comment]
The same simulation ran with "Input files" is displayed correctly when using master branch:

image
image

**Review by grzanka — CHANGES_REQUESTED** [review]
Fix doesn't work with results obtained with "Run with input files" method

**Comment by grzanka** [comment]
As for now you can disable grouping when presenting output for "input files" generated output

**Review by grzanka — APPROVED** [review]

**Review by Derstilon — APPROVED** [review]

**Pull request merged**
