### PR TITLE
# use endpoint for deleting specific simulation

### PR DESCRIPTION
**Pull request by matuszsmig**
Related PR on backend https://github.com/yaptide/yaptide/pull/1077

### CODE REVIEW

**Comment by grzanka** [comment]
I haven't tested this myself, but I am curious, which type of simulations can be cancelled this way: submitted to celery ("direct") or submitted to HPC cluster ("batch") ?

**Comment by grzanka** [comment]
@matuszsmig how that should work in fact ?

Is it the small X that should delete the simulation, or something else in the UI ?
image

If I click on X it displays popup "Delete local data" which doesn't make much sense now.

**Comment by grzanka** [comment]
Clicking `Cancel` should not delete the simulation ! The popup text should be improved

**Comment by matuszsmig** [comment]
I separated delete callback to two different callback (cancel and delete) and changed tooltip.
Delete button is small "X" in top right corner, cancel is first button in bottom buttuns

**Comment by grzanka** [comment]
I cannot remove cancelled simulations, I would like to be able to do so:

image

**Comment by matuszsmig** [comment]
@grzanka So if simulation is cancelled this "Retry" button should change into delete (x) button?

**Comment by grzanka** [comment]
> @grzanka So if simulation is cancelled this "Retry" button should change into delete (x) button?

Yes, exactly. This retry button if I remember correctly was intended to fetch again status of simulation

**Comment by grzanka** [comment]
I've deleted `yaptide_data` volume to start with fresh environment locally (means empty database), added a local user, ran some simulation and deleted it. I was suprised that deleted simulation card was removed only 10 seconds later after I clicked on Delete X button. Why wasn't that immediate ?

See movie below. I click delete around 1:10, simulation card is gone   around 1:20

[Screencast from 2024-10-07 18-40-12.webm](https://github.com/user-attachments/assets/5ddaadc8-b595-4ad2-a117-7b313c4f89bc)

Was that I had to wait 10 seconds for subsequent call to `
https://127.0.0.1:8443/user/simulations?page_idx=1&page_size=6&order_type=descend&order_by=start_time` ?

**Comment by matuszsmig** [comment]
I have made some refactoring so I added @tudde to reviewers.

Also changed that if simulation is state "CANCELLED" it is possible now to delete it.

I used kind of trick, when x is being pressed (delete) I am not only calling delete request, but also delete it from REACT's state, is it good aproach? @grzanka

**Comment by grzanka** [comment]
@ostatni5 maybe your advice here may help ?

**Comment by matuszsmig** [comment]
> > I have made some refactoring so I added @tudde to reviewers.
> > Also changed that if simulation is state "CANCELLED" it is possible now to delete it.
> 
> I havent made any tests yet, so cannot say how does it work now
> 
> > I used kind of trick, when x is being pressed (delete) I am not only calling delete request, but also delete it from REACT's state, is it good aproach? @grzanka
> 
> what if delete request is not successful ? there may be another request - before deleting ask user if he/she really wants to delete something, does it change your hack ?

I don't know what would be if request would fail there should be thrown some error, I may add some prompt asking if you are sure to delete it, it wouldn't change my hack. I think that is common approach

**Comment by grzanka** [comment]
I've merged related PR on backend, hence this code needs now to be tested with `master` branch on backend

**Comment by ostatni5** [comment]
> > > I have made some refactoring so I added @tudde to reviewers.
> > > Also changed that if simulation is state "CANCELLED" it is possible now to delete it.
> > 
> > 
> > I havent made any tests yet, so cannot say how does it work now
> > > I used kind of trick, when x is being pressed (delete) I am not only calling delete request, but also delete it from REACT's state, is it good aproach? @grzanka
> > 
> > 
> > what if delete request is not successful ? there may be another request - before deleting ask user if he/she really wants to delete something, does it change your hack ?
> 
> I don't know what would be if request would fail there should be thrown some error, I may add some prompt asking if you are sure to delete it, it wouldn't change my hack. I think that is common approach

When deleting a resource it is a good idea to ask the user for confirmation if this action is irreversible.
Optimistic updates are ok, but if an action fails app should be able to recover valid state by restoring old one or just by fetching the current one.

**Comment by grzanka** [comment]
> > > > I have made some refactoring so I added @tudde to reviewers.
> > > > Also changed that if simulation is state "CANCELLED" it is possible now to delete it.
> > > 
> > > 
> > > I havent made any tests yet, so cannot say how does it work now
> > > > I used kind of trick, when x is being pressed (delete) I am not only calling delete request, but also delete it from REACT's state, is it good aproach? @grzanka
> > > 
> > > 
> > > what if delete request is not successful ? there may be another request - before deleting ask user if he/she really wants to delete something, does it change your hack ?
> > 
> > 
> > I don't know what would be if request would fail there should be thrown some error, I may add some prompt asking if you are sure to delete it, it wouldn't change my hack. I think that is common approach
> 
> When deleting a resource it is a good idea to ask the user for confirmation if this action is irreversible. Optimistic updates are ok, but if an action fails app should be able to recover valid state by restoring old one or just by fetching the current one.

@ostatni5 and what do you think of refactoring, to my looks OK, but you are much more familiar with this code

**Review by grzanka — APPROVED** [review]
works well, needs documentation but thats an separate issue.

**Comment by grzanka** [comment]
Here is an issue related to documentation of this feature: https://github.com/yaptide/docs/issues/72

**Comment by grzanka** [comment]
@matuszsmig should we make this a regular PR, not a draft ?

**Comment by matuszsmig** [comment]
@grzanka i need to add this prompt which asks user if he is sure to delete it and I wany to test one thing

**Comment by grzanka** [comment]
> @grzanka i need to add this prompt which asks user if he is sure to delete it and I want to test one thing

Lets make it in the subsequent PR. If @tudde would comment today on the PR then lets wait for the review.
Otherwise lets squash-merge it.

**Comment by grzanka** [comment]
ok, no review from @tudde , merging

**Pull request merged**
